function RLC_Functie(r,l,c,v,yy,ff)
close all;

f=5:75;
T=1/ff;
t=0:T/100:5*T;

fprintf('f = %f\n', f);
xl=2*pi*f*l; %reactanta inductiva
xc=(1./(2*pi*f*c*10^(-6))); %reactanta capacitiva
fprintf('xl = %f\n', xl);
fprintf('xc = %f\n', xc);
%x=xl-xc;
bl=1./xl; %susceptanta inductiva
bc=1./xc; %susceptanta capacitiva
b=bl-bc;
g=1/r; %Ir
y=sqrt((g^2)+(b.^2)); %Admitanta circuitului
i=v.*y; %curentul total

%Tensiunea si curentii----------------
xll=2*pi*ff*l; %reactanta inductiva
xcc=(1./(2*pi*ff*c*10^(-6))); %reactanta capacitiva

u=v*sqrt(2)*sin(2*pi*ff*t);

ir=sqrt(2)*v/r*sin(2*pi*ff*t);
il=sqrt(2)*v/xll*sin(2*pi*ff*t-pi/2);
ic=sqrt(2)*v/xcc*sin(2*pi*ff*t+pi/2);

iii=ir+il+ic;
%---------------------------------------

figure('Name','RLC Paralel',...
 'Units','normalized',...
 'Position',[0.1 0.1 0.8 0.8],...
 'NumberTitle','off','color','#d9d9d9');

Group1=uibuttongroup('Visible','on',...
 'BackgroundColor','#cccccc',...
'ForegroundColor','black',...
 'Title','Modificari Parametri:',...
 'FontSize',10,...
'TitlePosition','centertop',...
 'Tag','radiobutton',...
 'Position',[0.08 0.5 0.4 0.5]); 



uicontrol('Style','pushbutton',... % pushbuton CLOSE
 'Units','normalized',...
 'Position',[0.8 0.9 0.18 .09],...
 'string','Close',...
 'Parent',Group1,... 
 'Callback','close');

uicontrol('Style','pushbutton',... % buton de reset
 'Units','normalized',...
 'Position',[0.8 0.77 0.18 .09],...
 'string','RESET',...
 'Parent',Group1,... 
 'Callback','close; RLC_Functie(60,0.1,25,220,1,100)');

%PopMenu
uicontrol('Style','popup',...
             'Units','normalized',...
             'Position',[0.05 0.9 .342 .05],...
             'string','Graficele I(A) & Y / HZ|Graficele BL & BC / HZ|Curenti|Tensiunea prin R,L si C',...
             'Value',yy,...
             'Parent',Group1,... 
             'Callback','yy=get(gco,''value''),close,RLC_Functie(r,l,c,v,yy,ff)');

%slider volt
uicontrol('Style','slider',...
             'Units','normalized',...
             'Position',[0.05 0.64 .26 .065],...
             'Min',0,'Max',300,'Value',v,...
             'sliderstep',[1/(300-0) 1/(300-0)],...
             'sliderstep',[1/(300-0) 1.5/(300-0)],...
             'Parent',Group1,... 
             'Callback','v=(get(gcbo,''value'')),close,RLC_Functie(r,l,c,v,yy,ff)');

%Scris Slider
uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.32 0.64 .14 .065],...
 'backgroundcolor','#d9d9d9',...
 'FontSize', 15,...
  'Parent',Group1,... 
 'foregroundcolor','black',...
 'String',v,...
 'Callback','v=str2num(get(gcbo,''String'')),close,RLC_Functie(r,l,c,v,yy,ff)');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.46 0.64 .07 .07],...
 'FontSize', 15,...
 'backgroundcolor','#cccccc',...
 'foregroundcolor','black',...
  'Parent',Group1,... 
 'String','V');

%Rezistenta

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.05 0.41 0.08 0.09],...
 'backgroundcolor','#cccccc',...
 'FontSize', 15,...
  'Parent',Group1,... 
 'foregroundcolor','black',...
 'String','R =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.15 0.43 0.095 0.09],...
 'foregroundcolor','black',...
 'FontSize', 15,...
 'backgroundcolor','#d9d9d9',...
 'String',r,...
 'Parent',Group1,... 
 'Callback','r=str2num(get(gcbo,''String'')),close,RLC_Functie(r,l,c,v,yy,ff)');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.24 0.41 0.15 0.1],...
 'backgroundcolor','#cccccc',...
 'FontSize', 15,...
  'Parent',Group1,... 
 'foregroundcolor','black',...
 'String','Ohm');

%Bobina

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.05 0.31 0.08 0.09],...
 'backgroundcolor','#cccccc',...
 'FontSize', 15,...
  'Parent',Group1,... 
 'foregroundcolor','black',...
 'String','L =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.15 0.33 0.095 0.09],...
 'foregroundcolor','black',...
 'FontSize', 15,...
 'backgroundcolor','#d9d9d9',...
 'String',l,...
 'Parent',Group1,... 
 'Callback','l=str2num(get(gcbo,''String'')),close,RLC_Functie(r,l,c,v,yy,ff)');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.24 0.31 0.1 0.1],...
 'backgroundcolor','#cccccc',...
 'FontSize', 15,...
  'Parent',Group1,... 
 'foregroundcolor','black',...
 'String','H');

%Condensator

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.05 0.21 0.08 0.09],...
 'backgroundcolor','#cccccc',...
 'FontSize', 15,...
  'Parent',Group1,... 
 'foregroundcolor','black',...
 'String','C =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.15 0.23 0.095 0.09],...
 'foregroundcolor','black',...
 'FontSize', 15,...
 'backgroundcolor','#d9d9d9',...
 'String',c,...
 'Parent',Group1,... 
 'Callback','c=str2num(get(gcbo,''String'')),close,RLC_Functie(r,l,c,v,yy,ff)');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.24 0.21 0.1 0.1],...
 'backgroundcolor','#cccccc',...
 'FontSize', 15,...
  'Parent',Group1,... 
 'foregroundcolor','black',...
 'String','μF');

if (r<0)||(l<0)||(c<0)||(v<0)||(ff<0)
    
uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.401 0.85 0.379 0.17],...
 'FontSize', 15,...
 'backgroundcolor','#ff3333',...
 'Parent',Group1,... 
 'foregroundcolor','black',...
 'String','Nu este permisa valoare negativa!!!'); 
end

subplot(222);
im = imread('imagine.png');
image(im);
set(gca,'visible','off')

if yy==1
 
subplot(223);
plot(f,i);
grid;
xlabel('Frecventa(Hz)','color', 'r');
ylabel('I(A) (Curentul Total)','color', 'b');

subplot(224);
plot(f,y);
grid;
xlabel('Frecventa(Hz)','color', 'r');
ylabel('Y (Admitanta)','color', 'b'); %admitanta


elseif yy==2
subplot(223);
plot(f,bl);
grid;
xlabel('Frecventa(Hz)','color', 'r');
ylabel('BL (Susceptanta Inductiva)','color', 'b');

subplot(224);
plot(f,bc);
grid;
xlabel('Frecventa(Hz)','color', 'r');
ylabel('BC (Susceptanta Capacitiva)','color', 'b');



elseif yy==3

  uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.45 0.41 0.08 0.09],...
 'backgroundcolor','#cccccc',...
 'FontSize', 15,...
  'Parent',Group1,... 
 'foregroundcolor','black',...
 'String','f =');

uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.55 0.43 0.095 0.09],...
 'foregroundcolor','black',...
 'FontSize', 15,...
 'backgroundcolor','#d9d9d9',...
 'String',ff,...
 'Parent',Group1,... 
 'Callback','ff=str2num(get(gcbo,''string'')),close,RLC_Functie(r,l,c,v,yy,ff)');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.64 0.41 0.09 0.1],...
 'backgroundcolor','#cccccc',...
 'FontSize', 15,...
  'Parent',Group1,... 
 'foregroundcolor','black',...
 'String','Hz');


%--------graficul tensiunilor--------
subplot (212)
plot(t,ir);
plot(t,iii,'g',t,ir,'b',t,il,'r',t,ic,'m');
grid on;
title('Curenti','Fontsize',13);
xlabel('Timp [s]','FontSize',12);
ylabel('i, ir, il, ir [A]','FontSize',12);
legend('i=ir+il+ic','ir - pe R ','il - pe L','ic - pe C');

elseif yy==4

     uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.45 0.41 0.08 0.09],...
 'backgroundcolor','#cccccc',...
 'FontSize', 15,...
  'Parent',Group1,... 
 'foregroundcolor','black',...
 'String','f =');

    uicontrol('Style','edit',...
 'Units','normalized',...
 'Position',[0.525 0.412 0.13 0.09],...
 'foregroundcolor','black',...
 'FontSize', 15,...
 'backgroundcolor','#d9d9d9',...
 'String',ff,...
 'Parent',Group1,... 
 'Callback','ff=str2num(get(gcbo,''string'')),close,RLC_Functie(r,l,c,v,yy,ff)');

uicontrol('Style','text',...
 'Units','normalized',...
 'Position',[0.64 0.41 0.09 0.1],...
 'backgroundcolor','#cccccc',...
 'FontSize', 15,...
  'Parent',Group1,... 
 'foregroundcolor','black',...
 'String','Hz');
%--------graficul curentului--------

subplot (212)
plot(t,u,'b');grid on;
title('Tensiunea prin R,L si C','Fontsize',13);
ylabel('[V]','FontSize',12);
xlabel('Timp [s]','FontSize',12);
end
